---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: services
spec:
  interval: 5m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${LB_HAJIMARI}

    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1

    env:
      TZ: "${TZ}"

    hajimari:
      defaultEnable: false
      namespaceSelector:
        any: true

      name: "Chris"
      groups:
        - name: Git
          links:
            - name: k8s-home-ops
              url: https://github.com/cbc02009/k8s-home-ops
            #     - name: Trux Home Assistant
            #       url: https://github.com/Truxnell/hass-config
            - name: k@h charts
              url: https://github.com/k8s-at-home/charts/tree/master/charts

    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
          prometheus.io/probe: "true"
          prometheus.io/protocol: http

        hosts:
          - host: "hajimari.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

        tls:
          - secretName: tls.hajimari
            hosts:
              - "hajimari.${EXTERNAL_DOMAIN}"

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 17m
        memory: 64M
