---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-webhook-token
    template:
      data:
        token: "{{ .flux_github_webhook_token }}"
  dataFrom:
    - extract:
        key: github
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "flux_$1"
