---
clusterName: kokoro

talosVersion: v1.3.5
kubernetesVersion: v1.26.1
endpoint: https://cluster.ctec.run:6443

allowSchedulingOnMasters: true

additionalApiServerCertSans:
  - 10.0.0.9

additionalMachineCertSans:
  - 10.0.0.9
  - cluster.local
  - cluster.ctec.run
clusterPodNets:
  - 10.11.0.0/16
clusterSvcNets:
  - 10.10.0.0/16
cniConfig:
  name: none

nodes:
  - hostname: uiharu.ctec.run
    ipAddress: 10.0.0.10
    installDiskSelector:
      serial: PHKA1261000X1P0B
    controlPlane: true
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.0.0.90
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.10/23
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        vip:
          ip: 10.0.0.9

  - hostname: anya.ctec.run
    ipAddress: 10.0.0.11
    installDiskSelector:
      model: KingFast
    controlPlane: true
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.0.0.90
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.11/23
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        vip:
          ip: 10.0.0.9

  - hostname: sakura.ctec.run
    ipAddress: 10.0.0.12
    installDiskSelector:
      model: INTEL SSDPEKNW512G8
    controlPlane: true
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.0.0.90
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.12/23
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        vip:
          ip: 10.0.0.9

  - hostname: rem.ctec.run
    ipAddress: 10.0.0.13
    installDiskSelector:
      model: FPT310M8SSD256G
    controlPlane: false
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.0.0.90
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.13/23
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1

  - hostname: ram.ctec.run
    ipAddress: 10.0.0.14
    installDiskSelector:
      model: FPT310M8SSD256G
    controlPlane: false
    disableSearchDomain: true
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.0.0.90
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.14/23
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1

controlPlane:
  inlinePatch:
    cluster:
      apiServer:
        admissionControl: []
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      allowSchedulingOnMasters: true
      controllerManager:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      discovery:
        registries:
          service:
            disabled: true
      proxy:
        disabled: true
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      scheduler:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
    machine:
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          op: create
          path: /etc/cri/conf.d/20-customization.part
      # install:
      #   extraKernelArgs:
      #     - talos.logging.kernel=udp://vector.kokoro.wtf:6050/
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: 'true'
      # logging:
      #   destinations:
      #     - endpoint: udp://vector.kokoro.wtf:6051/
      #       format: json_lines
      sysctls:
        fs.inotify.max_user_instances: '8192'
        fs.inotify.max_user_watches: '1048576'
      time:
        disabled: false
        servers:
          - time.cloudflare.com

worker:
  inlinePatch:
    cluster:
      discovery:
        registries:
          service:
            disabled: true
    machine:
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          op: create
          path: /etc/cri/conf.d/20-customization.part
      # install:
      #   extraKernelArgs:
      #     - talos.logging.kernel=udp://vector.kokoro.wtf:6050/
      kubelet:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
          rotate-server-certificates: 'true'
      # logging:
      #   destinations:
      #     - endpoint: udp://vector.kokoro.wtf:6051/
      #       format: json_lines
      sysctls:
        fs.inotify.max_user_instances: '8192'
        fs.inotify.max_user_watches: '1048576'
      time:
        disabled: false
        servers:
          - time.cloudflare.com
