---
logger:
  default: info
  logs:
    frigate.record: debug

mqtt:
  host: emqx.home-automation.svc.cluster.local
  topic_prefix: frigate
  user: mqtt
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  # https://github.com/blakeblackshear/frigate/issues/3296
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac

rtmp:
  enabled: true

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 7

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 7
      mode: active_objects

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

cameras:
  frigate_doorbell:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://10.0.0.110/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=${DOORBELL_USER}&password=${DOORBELL_PASS}
          roles:
            - rtmp
            - record
        - path: http://10.0.0.110/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=${DOORBELL_USER}&password=${DOORBELL_PASS}
          roles:
            - detect
          global_args: -analyzeduration 1000M -probesize 1000M
    detect:
      width: 640
      height: 480
      fps: 10
#   frigate_porch:
#     ffmpeg:
#       inputs:
#         - path: rtsp://192.168.1.2:7447/AiOhH1gQMPUcsRGC
#           roles:
#             - detect
#         - path: rtsp://192.168.1.2:7447/b8HED7as797Fr8J2
#           roles:
#             - rtmp
#             - record
#     detect:
#       width: 960
#       height: 720
#       fps: 10
#     objects:
#       filters:
#         person:
#           mask:
#             - 39,445,199,427,198,263,36,228
#             - 304,218,304,408,198,434,198,262
#             - 305,411,485,382,615,393,612,335,578,321,574,233,549,118,308,209

#   frigate_driveway:
#     ffmpeg:
#       inputs:
#         - path: rtsp://192.168.1.2:7447/Bbu0H4JuPjzK6zy9
#           roles:
#             - detect
#         - path: rtsp://192.168.1.2:7447/vixHJ1htwDadpDgE
#           roles:
#             - rtmp
#             - record
#     detect:
#       width: 1280
#       height: 720
#       fps: 10
#     objects:
#       filters:
#         person:
#           mask:
#             - 822,204,1280,360,1280,0,0,0,0,313

#   frigate_garage:
#     ffmpeg:
#       inputs:
#         - path: rtsp://192.168.1.2:7447/3mzDU0htPbIcPPFH
#           roles:
#             - detect
#         - path: rtsp://192.168.1.2:7447/Cpb9YqiSgX16LjsX
#           roles:
#             - rtmp
#             - record
#     detect:
#       width: 1024
#       height: 576
#       fps: 10

#   frigate_river:
#     ffmpeg:
#       inputs:
#         - path: rtsp://192.168.1.2:7447/GtBsJuujvMQwA42n
#           roles:
#             - detect
#         - path: rtsp://192.168.1.2:7447/b2K0uh13iekTbyA1
#           roles:
#             - rtmp
#             - record
#     detect:
#       width: 1024
#       height: 576
#       fps: 10

#   frigate_living_room:
#     ffmpeg:
#       inputs:
#         - path: rtsp://192.168.1.2:7447/PgTHLlRmqRH6Z6wV
#           roles:
#             - detect
#         - path: rtsp://192.168.1.2:7447/dGFODTTigTod247N
#           roles:
#             - rtmp
#             - record
#     detect:
#       width: 1024
#       height: 576
#       fps: 10

#   frigate_basement_1:
#     ffmpeg:
#       inputs:
#         - path: rtsp://192.168.1.2:7447/pBqg5G9dNfdYgwOA
#           roles:
#             - detect
#         - path: rtsp://192.168.1.2:7447/IgCuM7bT4pqFsDQU
#           roles:
#             - rtmp
#             - record
#     detect:
#       width: 1280
#       height: 720
#       fps: 10
