---
# yaml-language-server stuff goes here
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-ingress-nginx
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/network/ingress-nginx/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: network
  dependsOn:
    - name: apps-ingress-nginx-certificates
    - name: apps-kyverno
---
# yaml-language-server stuff goes here
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-ingress-nginx-certificates
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/network/ingress-nginx/certificates/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: apps-cert-manager-issuers
