---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "cutil-dev"
  namespace: network
spec:
  secretName: "cutil-dev-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${EXTERNAL_DOMAIN}"
  dnsNames:
    - "${EXTERNAL_DOMAIN}"
    - "*.${EXTERNAL_DOMAIN}"
  privateKey:
    algorithm: ECDSA
    size: 384
