---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system.yaml
  - kyverno.yaml
  - storage.yaml
  - monitoring.yaml
  - kube-system.yaml
  - network.yaml
  - cert-manager.yaml
