---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: services
data:
  DB_PORT: "5432"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_HOSTNAME: immich-redis.services.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "10"
  TYPESENSE_HOST: immich-typesense.services.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config
  IMMICH_WEB_URL: http://immich-web.services.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.services.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.services.svc.cluster.local:3003
