---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-secret
    creationPolicy: Owner
    template:
      data:
        KOPIA_FS_PATH: /repository_kopia
        KOPIA_PASSWORD: "{{ .kopia_password }}"
        KOPIA_REPOSITORY: filesystem:///repository_kopia
  dataFrom:
    - extract:
        key: volsync-template
