---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ctec-run
spec:
  secretName: ctec-run-tls
  issuerRef:
    name: letsencrypt-production
    # name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: ctec.run
  dnsNames:
    - "ctec.run"
    - "*.ctec.run"
