---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name vaultwarden
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Vaultwarden
        DATABASE_URL: "postgresql://{{ .VAULTWARDEN_STORAGE_POSTGRES_USERNAME }}:{{ .VAULTWARDEN_STORAGE_POSTGRES_PASSWORD }}@${POSTGRES_HOST}/vaultwarden"
        VAULTWARDEN_STORAGE_POSTGRES_USERNAME: "{{ .VAULTWARDEN_STORAGE_POSTGRES_USERNAME }}"
        VAULTWARDEN_STORAGE_POSTGRES_PASSWORD: "{{ .VAULTWARDEN_STORAGE_POSTGRES_PASSWORD }}"
        ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
        # Postgres Init
        POSTGRES_DB: vaultwarden
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .VAULTWARDEN_STORAGE_POSTGRES_PASSWORD }}"
        POSTGRES_USER: "{{ .VAULTWARDEN_STORAGE_POSTGRES_USERNAME }}"
  dataFrom:
    - extract:
        key: *name
    - extract:
        key: postgres
