---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "lanraragi-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        KOPIA_PASSWORD: "{{ .kopia_password }}"
        KOPIA_REPOSITORY: s3://volsync
        KOPIA_S3_DISABLE_TLS: "true"
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        AWS_S3_ENDPOINT: garage.ctec.internal:3900
  dataFrom:
    - extract:
        key: volsync
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lanraragi
spec:
  sourcePVC: "lanraragi"
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - "ReadWriteOnce"
    cacheAccessModes:
      - "ReadWriteOnce"
    cacheCapacity: "5Gi"
    cacheStorageClassName: "openebs-hostpath"
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 9001
      runAsGroup: 9001
      fsGroup: 9001
    parallelism: 2
    repository: "lanraragi-volsync"
    retain:
      hourly: 24
      daily: 7
    storageClassName: "ceph-block"
    volumeSnapshotClassName: "csi-ceph-blockpool"
