---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: external.kokoro.wtf
spec:
  endpoints:
    - dnsName: external.kokoro.wtf
      recordType: CNAME
      targets:
        - ${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com
