---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./babybuddy/ks.yaml
  - ./cyberchef/ks.yaml
  # - ./epic-freegames/ks.yaml
  - ./hajimari/ks.yaml
  - ./immich/ks.yaml
  - ./language-tools/ks.yaml
  - ./libreddit/ks.yaml
  - ./nextcloud/ks.yaml
  - ./obico/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./teddit/ks.yaml
  - ./theme-park/ks.yaml
  - ./whoogle/ks.yaml
