---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        KOPIA_PASSWORD: "{{ .kopia_password }}"
        KOPIA_REPOSITORY: s3://volsync
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        # KOPIA_S3_ENDPOINT: s3.ctec.run
        KOPIA_S3_DISABLE_TLS: "true"
        KOPIA_S3_ENDPOINT: "garage.ctec.internal:3900"
        # KOPIA_S3_ENDPOINT: "10.7.0.4:3900"
  dataFrom:
    - extract:
        key: volsync
