---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: 0 * * * *
  kopia:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce} # Use ReadOnlyMany for CephFS
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CACHE_CAPACITY:=5Gi}
    cacheStorageClassName: ${VOLSYNC_CACHE_STORAGECLASS:=openebs-hostpath}
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${APP_UID:=2000}
      runAsGroup: ${APP_GID:=2000}
      fsGroup: ${APP_GID:=2000}
    parallelism: 2
    repository: "${APP}-volsync"
    retain:
      hourly: 24
      daily: 7
    storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}
