---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./github-deploy-key.sops.yaml
  - ./cluster-secrets.sops.yaml
  - ./cluster-config.yaml
  - ./porkbun-key.sops.yaml
  - ./postgres.sops.yaml
