---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 30Gi
    storageClass: openebs-zfspv
  superuserSecret:
    name: postgres-superuser
  affinity:
    enablePodAntiAffinity: true #default value
    topologyKey: kubernetes.io/hostname #defaul value
    podAntiAffinityType: required
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: http://${SAN_HOST}:9000
      serverName: postgres-v1
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY

  # bootstrap:
  #   recovery:
  #     source: clusterBackup

  # externalClusters:
  #   - name: clusterBackup
  #     barmanObjectStore:
  #       destinationPath: s3://postgresql/
  #       endpointURL: https://s3.${EXTERNAL_DOMAIN}
  #       s3Credentials:
  #         accessKeyId:
  #           name: postgres-minio
  #           key: MINIO_ACCESS_KEY
  #         secretAccessKey:
  #           name: postgres-minio
  #           key: MINIO_SECRET_KEY
  #       wal:
  #         maxParallel: 8
