---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_NAME: nas
  CLUSTER_ID: "1"

  NETWORK_K8S_POD_CIDR: 10.12.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.11.0.0/16

  TZ: America/New_York

  NAS_HOST: 10.0.2.4

  # Pre-defined IP addresses
  # 10.0.2.142 - 10.0.2.150
  LB_OPC: 10.0.2.142
