---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name booklore
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: booklore_mariadb_password
      remoteRef:
        key: Booklore
        property: mariadb_password
    - secretKey: booklore_mariadb_root_password
      remoteRef:
        key: Booklore
        property: mariadb_root_password
