---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - actions-runner-controller-charts.yaml
  - authelia-charts.yaml
  - bjw-s-charts.yaml
  - cilium-charts.yaml
  - emqx-charts.yaml
  - external-dns-charts.yaml
  - fairwinds-charts.yaml
  - gitea-charts.yaml
  - grafana-charts.yaml
  - kyverno-charts.yaml
  - jetstack-charts.yaml
  - k8s-gateway-charts.yaml
  - kured-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - kubernetes-sigs-metrics-server-charts.yaml
  - kubernetes-sigs-nfd-charts.yaml
  - k8s-at-home-charts.yaml
  - lwolf-charts.yaml
  - metallb-charts.yaml
  - nextcloud-charts.yaml
  - openebs-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - democratic-csi-charts.yaml
  - bitnami-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - stakater-charts.yaml
  - vector-charts.yaml
