---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-iscsi-smoltank
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 5m
  values:

    csiDriver:
      name: "org.democratic-csi.iscsi"

    storageClasses:
      - name: csi-iscsi-smoltank
        defaultClass: false
        reclaimPolicy: Delete
        ## For testing
        # reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4

    controller:
      driver:
        image: ghcr.io/cbc02009/democratic-csi:v1.7.7
        imagePullPolicy: IfNotPresent

    driver:
      image: ghcr.io/cbc02009/democratic-csi:v1.7.7
      imagePullPolicy: IfNotPresent
      config:
        driver: zfs-generic-iscsi
      existingConfigSecret: zfs-generic-iscsi-config

    node:
      driver:
        image: ghcr.io/cbc02009/democratic-csi:v1.7.7
        imagePullPolicy: IfNotPresent

    csiProxy:
      image: ghcr.io/cbc02009/csi-grpc-proxy:v0.5.3
      imagePullPolicy: IfNotPresent
