---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  DB_PORT: "5432"
  NODE_ENV: "production"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.selfhosted.svc.cluster.local:3003
  IMMICH_SERVER_URL: http://immich-server.selfhosted.svc.cluster.local:3001
  REDIS_HOSTNAME: dragonfly.databases.svc.cluster.local
  REDIS_PORT: "6379"
  TRANSFORMERS_CACHE: /usr/src/app/.transformers_cache
