---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - selector:
          dnsZones:
            - ${EXTERNAL_DOMAIN}
        dns01:
          webhook:
            groupName: acme.${EXTERNAL_DOMAIN}
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-key
                key: api-key
              secretKeySecretRef:
                name: porkbun-key
                key: secret-key
