---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector:
          dnsZones:
            - ${EXTERNAL_DOMAIN}
        dns01:
          cloudflare:
            email: ${ACME_EMAIL}
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_APIKEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - ${EXTERNAL_DOMAIN}
        dns01:
          cloudflare:
            email: ${ACME_EMAIL}
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_APIKEY
