---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/runnerdeployment_v1alpha1.json
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: containers-mirror
  namespace: dev
spec:
  template:
    spec:
      image: ghcr.io/actions/actions-runner-controller/actions-runner-dind:v2.299.1-ubuntu-22.04
      imagePullPolicy: IfNotPresent
      dockerdWithinRunnerContainer: false
      ephemeral: true
      repository: cbc02009/containers-mirror
      labels: ["self-hosted"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: actions-runner-controller-cache
---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/horizontalrunnerautoscaler_v1alpha1.json
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: containers-mirror
  namespace: dev
spec:
  scaleTargetRef:
    name: containers-mirror
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      amount: 1
      duration: 30m
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames: ["containers-mirror"]
