---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./containers-mirror.yaml
  - ./k8s-home-ops.yaml
metadata:
  namespace: dev
