---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/runnerdeployment_v1alpha1.json
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: vno-local-cpu
  namespace: dev
spec:
  template:
    spec:
      image: ghcr.io/actions/actions-runner-controller/actions-runner-dind:v2.299.1-ubuntu-22.04
      imagePullPolicy: IfNotPresent
      dockerdWithinRunnerContainer: true
      ephemeral: true
      repository: cbc02009/vno-local-cpu
      labels: ["self-hosted"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: actions-runner-controller-cache
---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/horizontalrunnerautoscaler_v1alpha1.json
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: vno-local-cpu
  namespace: dev
spec:
  scaleTargetRef:
    name: vno-local-cpu
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      amount: 1
      duration: 30m
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames: ["vno-local-cpu"]
