apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:5sbUujLbhNdvAbUXu88Qnl5xEL/gfQL2ylgd6dIn5I8=,iv:hSPTehQ0bh8r/cQjoXydDWiHq+QK2SBl8Nf0mfsOCUc=,tag:qYCOTf1YmsmEt5NimpKXvw==,type:str]
sops:
  age:
    - recipient: age1ayu5h4m5gqfchewyk6vqm2ts95n3q947lldcwf4cjclqx0kec5fq5dha7q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZmljNmYvQThEZG5rcjJn
        V1JNQmYzWStIWnJrOC90WGtwN0NpOVZJTENjCnpSVG5EcVBJNmt2S0luU2VicmN3
        aVZ6OTJ2Qzl0WWd4WS9PTDIwOVIzRGMKLS0tIGFVazUyY0ErZmc3SC9lRTZDdTAr
        dXExcjJDTVl2MEpLQXh3V0swNmk1bE0Kdcu5iGmZVW8MDHHLevWJR1PcSJF15rQx
        3H+JXqqs54A9bVs31vboytOv3UDj12MOTtk8SfSr9OTAEbKng9p2aA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1cv38ga8yzk2v035gvtqxkf6vzgy5smy6cjq0a303c75ffxtxpauq9sasm8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aWVXRkFxbG9MKzczRnFO
        Y3NDT0RhSGJxMTF2VGgvL1dLYXMrRURoKzBvCklXSHJMNk1seU51bHExK3JEY1Vy
        VHVjMVoxZVM3SW9JK3hXNzdNU3NQcm8KLS0tIHFDbFh0UHlYS2prbms4TnVRK1Bx
        OXBiNk9TVGhSMjVFR3hXRnJBdFBlZlEKmGR3HVs7RoPbNjBWsu7wT/bn/nT7qDbe
        3FlwKDSSbhJZQ5xB7GYkCgjR2NNY09n3vbzvm/aktfhzu+n+Gawv+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T17:10:07Z"
  mac: ENC[AES256_GCM,data:sRyEeysBITF3b1bVoy4CEeqp+HMre91y+KvCXDknZadsc6jaiRnUwqwXCnzqRyfQvhEsiHTOOqYUN00n719vDWcFwyjrwZey3KlBKthslYYmlECNMdINZTHxV0j6JJMIAkX9CRIxujb3So6ySVEWBZNm0Mlw/alL6s2qhMD6QlU=,iv:qB2yVZF5ruKnB8IcxvzmwGHWpzKSEOy3O2I/vbhBc9E=,tag:qU+2fP1DfC3mA31jNJ+WHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
