---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name coder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Coder
        CODER_PG_CONNECTION_URL: "postgres://{{ .pg_user }}{{ .pg_pass }}@{{ .postgres_host }}:5432/coder?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "coder"
        INIT_POSTGRES_HOST: "{{ .postgres_host }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_pass}}"
        INIT_POSTGRES_USER: "{{ .pg_user }}"
        INIT_POSTGRES_PASS: "{{ .pg_pass }}"
  dataFrom:
    - extract:
        key: coder
    - extract:
        key: postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
