---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local
      # connectHost: http://opc.ctec.run
      vaults:
        k8s-home-ops: 1
        Homelab: 2
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-secret
            key: token
            namespace: external-secrets
