---
working_dir: ./docker/truenas
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  TRAEFIK_CF_DNS_API_TOKEN: op://Homelab/cloudflare_nas/truenas_traefik_api_token
