machine:
  sysctls:
    fs.inotify.max_user_watches: "1048576"     # Watchdog
    fs.inotify.max_user_instances: "8192"      # Watchdog
    net.core.rmem_max: "7500000"               # Cloudflared | QUIC
    net.core.wmem_max: "7500000"               # Cloudflared | QUIC
    net.ipv4.neigh.default.gc_thresh1: "4096"  # Prevent ARP cache overflows
    net.ipv4.neigh.default.gc_thresh2: "8192"  # Prevent ARP cache overflows
    net.ipv4.neigh.default.gc_thresh3: "16384" # Prevent ARP cache overflows
    net.ipv4.tcp_slow_start_after_idle: "0"    # Preserve congestion window after idle
    user.max_user_namespaces: "11255"          # User Namespaces
    net.core.default_qdisc: fq
    net.ipv4.ping_group_range: 0 2147483647
    net.ipv4.tcp_congestion_control: bbr
    net.ipv4.tcp_fastopen: "3"
    net.ipv4.tcp_mtu_probing: "1"
    net.ipv4.tcp_notsent_lowat: "131072"
    net.ipv4.tcp_rmem: 4096 87380 33554432
    net.ipv4.tcp_window_scaling: "1"
    net.ipv4.tcp_wmem: 4096 65536 33554432
    sunrpc.tcp_max_slot_table_entries: "128"
    sunrpc.tcp_slot_table_entries: "128"
    vm.nr_hugepages: "1024"
