---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-terraform-s3
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/cbc02009/terraform-s3
  ref:
    tag: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: s3
  namespace: flux-system
spec:
  interval: 12h
  approvePlan: "auto"
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tf-controller-tfrc-secret
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: oci-terraform-s3
    namespace: flux-system
  runnerPodTemplate:
    spec:
      env:
        - name: OP_CONNECT_HOST
          value: http://onepassword-connect.kokoro.wtf:8080
        - name: OP_CONNECT_TOKEN
          valueFrom:
            secretKeyRef:
              name: tf-controller-op-secret
              key: OP_CONNECT_TOKEN
      volumeMounts:
        - name: tf-controller-sops-key
          mountPath: /home/runner/.config/sops/age/keys.txt
          subPath: keys.txt
      volumes:
        - name: tf-controller-sops-key
          secret:
            secretName: tf-controller-sops-secret
