---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./atuin/ks.yaml
  - ./cyberchef/ks.yaml
  - ./mealie/ks.yaml
  - ./immich/ks.yaml
  - ./it-tools/ks.yaml
  # - ./opencloud/ks.yaml
  - ./openspeedtest/ks.yaml
  # - ./paperless/ks.yaml
  - ./redlib/ks.yaml
  - ./rustdesk/ks.yaml
  - ./smtp-relay/ks.yaml
