---
# yaml-language-server stuff goes here
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificates.yaml
  # - ./certificate-staging.yaml
metadata:
  namespace: network
