---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - add-prom-probes.yaml
  # - inject-timezone.yaml
  - remove-cpu-limit.yaml
  - set-internal-ingress-annotations.yaml
  - sync-postgres-secret.yaml
  # - ./snapshot-cronjob-controller.yaml
  # - add-vpn-caps.yaml
