---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../../shared/components/namespace
  - ../../../shared/components/flux/alerts
resources:
  - ./animarr/ks.yaml
  # - ./autobrr/ks.yaml
  - ./lidarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
