---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./actions-runner-controller-charts.yaml
  - ./angelnu-charts.yaml
  - ./aqua-charts.yaml
  - ./authelia-charts.yaml
  - ./backube-charts.yaml
  - ./bjw-s-charts.yaml
  - ./cilium-charts.yaml
  - ./cloudnative-pg.yaml
  - ./emqx-charts.yaml
  - ./external-dns-charts.yaml
  - ./external-secrets-charts.yaml
  - ./fairwinds-charts.yaml
  - ./gabe565-charts.yaml
  - ./grafana-charts.yaml
  - ./intel.yaml
  - ./kyverno-charts.yaml
  - ./jetstack.yaml
  - ./k8tz.yaml
  - ./kubernetes-sigs-descheduler-charts.yaml
  - ./kubernetes-sigs-metrics-server-charts.yaml
  - ./kubernetes-sigs-nfd-charts.yaml
  - ./lwolf-charts.yaml
  - ./mayastor.yaml
  - ./nextcloud-charts.yaml
  - ./nvidia.yaml
  - ./piraeus-charts.yaml
  - ./postfinance-charts.yaml
  - ./prometheus-community-charts.yaml
  - ./rook-ceph-charts.yaml
  - ./bitnami-charts.yaml
  - ./ingress-nginx-charts.yaml
  - ./stakater-charts.yaml
  - ./tf-controller.yaml
  - ./vector-charts.yaml
  - ./weave-gitops.yaml
