---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stevehipwell
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://ghcr.io/stevehipwell/helm-charts
