---
originRequest:
  originServerName: external.kokoro.wtf

ingress:
  - hostname: kokoro.wtf
    service: &svc https://envoy-external.network.svc.cluster.local
  - hostname: "*.kokoro.wtf"
    service: *svc
  - service: http_status:404
