---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./volsync.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./volsync-b2.yaml
metadata:
  namespace: media
