---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: stalednswarning
spec:
  matchers:
    - name: alertname
      value: ExternalDNSStale
