---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr-restic
  namespace: organizarrs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lidarr-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/lidarr'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lidarr
  namespace: organizarrs
spec:
  sourcePVC: lidarr-config-v1
  trigger:
    schedule: '0 0 * * *'
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: lidarr-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 10
      monthly: 3
      within: 3d
