---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name tandoor
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tandoor-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Tandoor
        POSTGRES_USER: "tandoor-user"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        SECRET_KEY: "{{ .SECRET_KEY }}"
        EMAIL_HOST: "{{ .EMAIL_HOST }}"
        EMAIL_PORT: "{{ .EMAIL_PORT }}"
        EMAIL_HOST_USER: "{{ .EMAIL_HOST_USER }}"
        EMAIL_HOST_PASSWORD: "{{ .EMAIL_HOST_PASSWORD }}"
        # Postgres Init
        POSTGRES_DB: "tandoor"
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_SUPER_PASS: "{{ .pg_password }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        # Minio Storage
        S3_BUCKET_NAME: tandoor
        S3_ENDPOINT_URL: "http://s3.ctec.run:9000"
        S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        S3_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: tandoor
    - extract:
        key: postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
