---
networks:
  apps:
    name: apps
    external: false
services:
  traefik:
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN}
    image: traefik:v3.6.8
    networks:
      - apps
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yaml
    ports:
      - 80:80
      - 443:443
    volumes:
      - acme:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/dynamic:/dynamic
configs:
  traefik-config:
    file: ./config/traefik.yaml
volumes:
  acme:
