---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - volsync.yaml
patchesStrategicMerge:
  - patches/addons.yaml
metadata:
  namespace: home-automation
