EMPTY: ENC[AES256_GCM,data:Q7+HFPI=,iv:tIEI3bfQi4iQa0qZJ2C4yJM/PeaLUh+5xg5h5PVnPO8=,tag:4Saz3SJ1XeCoTYgXC80zkA==,type:str]
sops:
    age:
        - recipient: age1ayu5h4m5gqfchewyk6vqm2ts95n3q947lldcwf4cjclqx0kec5fq5dha7q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SUZQcDBVWW9JY005UlMw
            aWlncVg0eCtWb05WZnR1UC9OV0dHWVRQSFh3CmQ3UVJNMjU0M3hXWEdRMEVFaUZo
            b2hSTTh6dVR5dU1IMlRrVkduNmVIdUUKLS0tIGNOVExCQTE4eWthaVBxNHBiZ3JV
            WFMxelNQQm5acGI1alpValFFZDRXZU0KQ1Xwikjctm7cJGDjIafuuvoUuqKIqPk6
            k8Esym7DA4nJ/rr2V2rpGVOXshKCX/9MHXsvrWhVu1OXVPPA3MkLgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:51:47Z"
    mac: ENC[AES256_GCM,data:BjLD5YUtQR//IMpIkQxfGf8foLDUya4e5kQeREV5Yk8N4wNh5vQQa/0j6dopM15adXtGk0InGn68TL14DFb8L6up5zsZy35CuNcTkiQep2f+YfRbZhD/rClROas9k415ll92d+uZOU2P/sooTsfRr7vBVzgpCshKgDet6p25Bqw=,iv:IqROYM85qt+IWzOYmcdhEttFr/DL5tWze+k8gowVxHA=,tag:hXLwfG55OhK7JwbfbLrkHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
