---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # - ../../../../components/gatus/external
  - ../../../../components/volsync
namespace: home-automation
configMapGenerator:
  - name: frigate
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
  # annotations:
  #   kustomize.toolkit.fluxcd.io/substitute: disabled
metadata:
  namespace: home-automation
