---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Paperless
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: &dbname paperless
        PAPERLESS_DBHOST: &host "{{ .postgres_host }}"
        PAPERLESS_DBUSER: &dbuser "{{ .pg_user }}"
        PAPERLESS_DBPASS: &dbpass "{{ .pg_pass }}"
        PAPERLESS_ADMIN_USER: "{{ .admin_user }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .admin_pass }}"
        PAPERLESS_SECRET_KEY: "{{ .secret_key }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *host
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_pass }}"
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        # OIDC
        PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
        PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
        PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Authentik",
                        "client_id": "{{ .oidc_id }}",
                        "secret": "{{ .oidc_secret }}",
                        "settings": {
                            "server_url": "https://auth.${EXTERNAL_DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
