---
# yaml-language-server stuff goes here
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-rook-ceph-cluster
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/rook-ceph/rook-ceph/cluster/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-cluster
      namespace: rook-ceph
  dependsOn:
    - name: apps-rook-ceph-operator
---
# yaml-language-server stuff goes here
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-rook-ceph-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/rook-ceph/rook-ceph/operator/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-operator
      namespace: rook-ceph
