apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:uRECm41qDddZV31ugBqMzNQXCuVOrGka79GYK4T2Ypt7i0jmv/Fq6s+qM/d283h6J5sEcoW9LDOi5oxAzxd9+iAPlsQ2rTLUrgk=,iv:UqvMDn2ZArFrRNDmPjhEUa4XuyVytAb6p+X8Va3kKxM=,tag:jwujWfGdPu5XM5CE+7djwQ==,type:str]
sops:
  age:
    - recipient: age1ayu5h4m5gqfchewyk6vqm2ts95n3q947lldcwf4cjclqx0kec5fq5dha7q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd2NLRjFRU1oweDZad3Zz
        ZkhqT2d2TWRFZUdob1RRbEFpOHFXK1VYRnpVCjIwTGw3aUdyQ0tCSzNZUG9XKzFx
        MTBaOXlwZ0Q5NG9QSk1vZWlQZnM2ZDQKLS0tICtrTit0NC9GYnovZWlVMFJ1UXgy
        YTVQdzltVkFrbC9oVXQ3MGVYZVVlMEEKSAQBqI6Nm31CHpDoGDqmPRRSx8WLKt5F
        7oh+nE7JDpUad9qWpvrUNc+HYnewFyLLbLHU2YS2qpS6INbOfLjnAQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1cv38ga8yzk2v035gvtqxkf6vzgy5smy6cjq0a303c75ffxtxpauq9sasm8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N2djaTltcmhpcU5wTGgr
        R3I2cUl5eWdwczdQam9PeVllM3czamtUcFFVCm1LazFNZXFUVVNXM0JGQy9GMnNs
        OE0xd0pXR2pnNUlvaXlxK1NlVEpGMzgKLS0tIDB4dldKZUl5TVVYazE3aTlIOTJU
        aHNieGRxQndZYTFMQmNEWldLRnlhdTQKaSzHpG914OzOKzsd288zfwm6Tr7Xwolv
        4Bb8XZjfYNYx5B7U1vXqQSNVEUq3QrTLGRdGoZTrhjOPMLDUzFi8rA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T17:03:35Z"
  mac: ENC[AES256_GCM,data:MaVq0HPv4RGKsn5AZYn99FAXUKdt8MmS3WeEpg+d398GUw+V3CWxfCmE7rmOb5+k6TchAVqSeD1HT8nhQC95XHez1HN+btBgnmBct85XTyBlrn0nrLEcckl0O90i1pCfmiKihhnlUjwtI8xsDB7IbP9idSnUgwfms6tMaqe1mfQ=,iv:wFXCiLwjbTc1RuAK2Udqhn02FrKs/3p/8WNv18phbe4=,tag:1BrUyMgi9Z6jOvKj6NWhJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
