---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: envoy-gateway
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: envoy-gateway
      namespace: network
  interval: 1h
  path: "./kubernetes/apps/network/envoy-gateway/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-config
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: envoy-gateway
  dependsOn:
    - name: envoy-gateway
      namespace: network
  interval: 1h
  path: "./kubernetes/apps/network/envoy-gateway/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
