metadata_dir = "/data/meta"
data_dir = "/data/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1
compression_level = "none"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "${GARAGE_RPC_SECRET}"

[s3_api]
s3_region = "us-east-1"
api_bind_addr = "[::]:3900"
root_domain = ".s3.ctec.run"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${GARAGE_ADMIN_TOKEN}"
metrics_token = "${GARAGE_METRICS_TOKEN}"
metrics_require_token = false
