---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./databases.yaml
  # - ./downloads.yaml
  - ./kube-system.yaml
  - ./home-automation.yaml
  - ./organizarrs.yaml
  - ./media.yaml
  - ./services.yaml
  - ./security.yaml
  - ./translation.yaml
  - ./monitoring.yaml
  - ./dev.yaml
  - ./vpn.yaml
