---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-authelia
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/security/authelia/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: authelia
      namespace: security
  dependsOn:
    - name: apps-external-secrets-stores
    - name: apps-glauth
    - name: apps-redis
